apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
           - targets: ["localhost:9090"]

      - job_name: "mysql"
        static_configs:
          - targets: ["mysql-exporter:9104"]

      - job_name: "redis"
        static_configs:
          - targets: ["redis-exporter-service:9121"]

      - job_name: "nginx"
        static_configs:
          - targets: ["nginx-exporter-service:9113"]

      - job_name: "flask"
        static_configs:
          - targets: ["flask-service:5000"]
