apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
spec:
  selector:
    matchLabels:
      app: db
  serviceName: "db"
  replicas: 3
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql-db
        image: mariadb:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: MYSQL_USER
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: MYSQL_ROOT_PASSWORD
        
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mariadb-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Mi
      storageClassName: "local-path"