apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: derradjisenani/backend_webapp:latest
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: az-configmap
              key: db-host
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: az-configmap
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: az-secret
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: az-secret
              key: password
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: REDIS_HOST
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: REDIS_PASSWORD
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 5000
