apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: myapp
        image: grafana/grafana:latest
        env:
        - name : GF_SECURITY_ADMIN_USER
          value : admin
        - name: GR_SECURITY_ADMIN_PASSWORD
          value: admin
        ports:
        - containerPort: 3000
