apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  # type: NodePort # Just for testing with k3s internal load balancer
  # type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
