name: Test Runner

on: [push]

jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
      - name: test
        run: |
          echo "hello world" >> test.txt
          cat test.txt
      # - name: Checkout code
      #   uses: actions/checkout@v3
      
      # - name: Run K8s Manifests
      #   run : |
      #     cd k8s/K3s/DEV-TEST
      #     sudo bash ./apply.sh
          