# name: CI_TEST

# on:
#   workflow_run:
#     workflows: ["CI_TEST.yaml"]

#     types:
#       - completed

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3