name: Semgrep Code Scan

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Semgrep
      - name: Setup Semgrep
        uses: returntocorp/semgrep-action@v1

      # Run Semgrep with default rules
      - name: Run Semgrep Scan
        run:  semgrep --config auto --error app/
