name: CI_TEST

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  # workflow_run:
  #   workflows: ["CI_DEV"]
  #   types:
  #     - completed

jobs:
  test_env:
    runs-on: ubuntu-latest
    environment:
      name: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Export ARM_* env vars for Terraform
        run: |
          echo "ARM_CLIENT_ID=$(echo '${{ secrets.AZURE_CRED }}' | jq -r .clientId)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(echo '${{ secrets.AZURE_CRED }}' | jq -r .clientSecret)" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(echo '${{ secrets.AZURE_CRED }}' | jq -r .subscriptionId)" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(echo '${{ secrets.AZURE_CRED }}' | jq -r .tenantId)" >> $GITHUB_ENV
      

      - name: Set SSH public key env (base64 encoded)
        run: |
         SSH_ENCODED=$(echo '${{ secrets.SSH_PUBLIC_KEY }}' | base64 -w 0)
         echo "SSH_PUBLIC_KEY_ENCODED=$SSH_ENCODED" >> $GITHUB_ENV
      
      

      - name: public key debug
        run: |
         echo $SSH_PUBLIC_KEY_ENCODED
         echo $SSH_PUBLIC_KEY_ENCODED | base64 -d
         SSH_PUBLIC_KEY=$(echo "$SSH_PUBLIC_KEY_ENCODED" | base64 -d)
         echo $SSH_PUBLIC_KEY
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform -chdir=IAC/envs/test init

      - name: Terraform Validate
        run: terraform -chdir=IAC/envs/test -var "ssh_public_key=$SSH_PUBLIC_KEY" validate

      - name: Terraform PLAN
        run: terraform -chdir=IAC/envs/test -var "ssh_public_key=$SSH_PUBLIC_KEY" validate

      
      - name: Terraform Apply
        run: terraform -chdir=IAC/envs/test -var "ssh_public_key=$SSH_PUBLIC_KEY" validate -auto-approve
