name: Test Runner

on: [push]

jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
      - name: Print hostname
        run: hostname

      - name: Show whoami
        run: whoami

      - name: List files
        run: ls -la
